// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.0.24839
//    <NameSpace></NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net30</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Generic;


public partial class Actor {
    
    private string firstnameField;
    
    private string lastnameField;
    
    private byte[] pictureField;
    
    private System.Nullable<bool> principalActorField;
    
    private string nationalityField;
    
    public Actor() {
        this.nationalityField = "US";
    }
    
    public string firstname {
        get {
            return this.firstnameField;
        }
        set {
            this.firstnameField = value;
        }
    }
    
    public string lastname {
        get {
            return this.lastnameField;
        }
        set {
            this.lastnameField = value;
        }
    }
    
    public byte[] picture {
        get {
            return this.pictureField;
        }
        set {
            this.pictureField = value;
        }
    }
    
    public bool PrincipalActor {
        get {
            if (this.principalActorField.HasValue) {
                return this.principalActorField.Value;
            }
            else {
                return default(bool);
            }
        }
        set {
            this.principalActorField = value;
        }
    }
    
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrincipalActorSpecified {
        get {
            return this.principalActorField.HasValue;
        }
        set {
            if (value==false) {
                this.principalActorField = null;
            }
        }
    }
    
    [System.ComponentModel.DefaultValueAttribute("US")]
    public string nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
}

public partial class DvdCollection {
    
    private List<dvd> dvdsField;
    
    public DvdCollection() {
        this.dvdsField = new List<dvd>();
    }
    
    public List<dvd> Dvds {
        get {
            return this.dvdsField;
        }
    }
}

public partial class dvd {
    
    private string yearField;
    
    private System.Nullable<System.DateTime> publishField;
    
    private string titleField;
    
    private Styles styleField;
    
    private List<Actor> actorField;
    
    private int publishYearField;
    
    private dvdCover coverField;
    
    public dvd() {
        this.coverField = new dvdCover();
        this.actorField = new List<Actor>();
        this.titleField = "DefaultTitle";
        this.styleField = Styles.Action;
    }
    
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    public System.Nullable<System.DateTime> Publish {
        get {
            return this.publishField;
        }
        set {
            this.publishField = value;
        }
    }
    
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    public Styles Style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    public List<Actor> Actor {
        get {
            return this.actorField;
        }
    }
    
    public int PublishYear {
        get {
            return this.publishYearField;
        }
        set {
            this.publishYearField = value;
        }
    }
    
    public dvdCover Cover {
        get {
            return this.coverField;
        }
        set {
            this.coverField = value;
        }
    }
}

public enum Styles {
    
    /// <remarks/>
    Action,
    
    /// <remarks/>
    Fiction,
}

public partial class dvdCover {
    
    private string systemeField;
    
    private string valueField;
    
    public string Systeme {
        get {
            return this.systemeField;
        }
        set {
            this.systemeField = value;
        }
    }
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

public partial class Actors {
    
    private List<Actor> actorField;
    
    public Actors() {
        this.actorField = new List<Actor>();
    }
    
    public List<Actor> Actor {
        get {
            return this.actorField;
        }
    }
}

public partial class mycttype {
    
    private double valueField;
    
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
